name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ui
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: yarn install, format, lint
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn run format:check
          yarn run lint
        working-directory: ${{ env.working-directory }}
      - name: yarn test
        run: yarn run test -- --coverage
        env:
          CI: true
        working-directory: ${{ env.working-directory }}
