name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ui
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: yarn install, format, lint
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn run format:check
          yarn run lint
        working-directory: ${{ env.working-directory }}
      - name: yarn test
        run: yarn run test -- --coverage
        env:
          CI: true
        working-directory: ${{ env.working-directory }}
      - name: Build Project
        if: github.event_name == 'push'
        run: yarn run build
        working-directory: ${{ env.working-directory }}
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain votevote-dev.surge.sh
        working-directory: ${{ env.working-directory }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
